(()=>{
const CASE=window.TRACCE_CASES.monet1, S=window.TracceStorage, API=window.TracceAPI;
const app=document.getElementById('app'), progress=document.getElementById('progress'), zoomBtn=document.getElementById('zoomBtn');
const help=document.getElementById('helpDialog'), helpTitle=document.getElementById('helpTitle'), helpBody=document.getElementById('helpBody');
const zoom=document.getElementById('zoomDialog'), zoomImage=document.getElementById('zoomImage');
const STEPS=['observe','look','clues','proof','compare','conclusion'];
const LABELS={observe:'OSSERVA',look:'GUARDA',clues:'INDIZI',proof:'PROVA',compare:'CONFRONTO',conclusion:'CONCLUSIONE'};
let state=null;

const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){S.save(state)}
function setStep(step){state.currentStep=step;save();render()}
function artwork(){return `<section class="art-panel"><img class="artwork" src="${CASE.image}" alt="${esc(CASE.imageAlt)}"><p class="caption"><strong>${CASE.artist}</strong>, <em>${CASE.artwork}</em>, ${CASE.year}<br>${CASE.museum} · Riproduzione: Wikimedia Commons, Public Domain Mark. <a href="${CASE.commonsPage}" target="_blank" rel="noopener">Fonte immagine</a></p></section>`}
function layout(body){return `<div class="work-layout">${artwork()}<section class="panel">${body}</section></div>`}
function nav(back,next,label='CONTINUA →',disabled=false){return `<div class="nav-row">${back?`<button class="btn btn-secondary" data-go="${back}">← INDIETRO</button>`:'<span></span>'}<button class="btn" id="nextBtn" data-go="${next}" ${disabled?'disabled':''}>${label}</button></div>`}
function renderProgress(){if(!STEPS.includes(state?.currentStep)){progress.classList.add('hidden');return}progress.classList.remove('hidden');const i=STEPS.indexOf(state.currentStep);progress.innerHTML=STEPS.map((s,n)=>`<span class="${n<i?'done':n===i?'current':''}">${n<i?'✓ ':''}${LABELS[s]}</span>`).join('')}
function openHelp(title,html){helpTitle.textContent=title;helpBody.innerHTML=html;help.showModal()}
function zoomWork(){zoomImage.src=CASE.image;zoomImage.alt=CASE.imageAlt;zoom.showModal()}
function render(){renderProgress();zoomBtn.classList.toggle('hidden',!state||['home','resume','success'].includes(state.currentStep));
 if(!state){renderHome();return} const fn={home:renderHome,observe:renderObserve,look:renderLook,clues:renderClues,proof:renderProof,compare:renderCompare,conclusion:renderConclusion,summary:renderSummary,success:renderSuccess}[state.currentStep]||renderHome;fn();bindCommon();app.focus();}
function renderHome(){progress.classList.add('hidden');zoomBtn.classList.add('hidden');const saved=S.load();if(saved&&saved.status!=='submitted'&&saved.currentStep!=='home'){app.innerHTML=`<section class="home panel"><h2>C'è un lavoro non ancora concluso</h2><p><strong>${esc(saved.group)}</strong><br>${esc(saved.artist)}<br><em>${esc(saved.artwork)}</em></p><div class="nav-row"><button id="restart" class="btn btn-danger">RICOMINCIA</button><button id="resume" class="btn">CONTINUA IL LAVORO</button></div></section>`;document.getElementById('resume').onclick=()=>{state=saved;render()};document.getElementById('restart').onclick=restart;return}
 app.innerHTML=`<section class="home"><h2>Tracce di Impressionismo</h2><p class="lead">Osserva. Cerca gli indizi. Sostieni la tua interpretazione.</p><div class="case-card"><h3>Gruppo 1</h3><p><strong>Claude Monet</strong><br><em>Campo di papaveri ad Argenteuil</em>, 1873</p><p>Lavorerete insieme su un'opera.<br>Osservate, confrontate le vostre idee e cercate prove nell'immagine.</p><button id="start" class="btn">INIZIA</button></div><p class="small">Non ci sono risposte da indovinare. Conta ciò che riuscite a sostenere osservando l'opera.</p></section>`;document.getElementById('start').onclick=()=>{state=S.fresh(CASE);state.currentStep='observe';save();render()}}
function restart(){if(confirm('Vuoi davvero cancellare il lavoro salvato su questo tablet?')){S.clear();state=null;render()}}
function renderObserve(){app.innerHTML=layout(`<h2>OSSERVA</h2><p class="lead"><strong>Osserva l'opera in silenzio.</strong></p><p>Non parlare ancora con il gruppo.<br>Cerca una cosa che ti colpisce.</p>${nav(null,'look','SIAMO PRONTI →')}`)}
function renderLook(){app.innerHTML=layout(`<h2>GUARDA</h2><p class="lead"><strong>Adesso confrontatevi.</strong></p><p>A turno, ognuno dica <strong>una cosa che ha notato</strong>.<br>Ascoltate anche ciò che hanno visto gli altri.</p><label for="free"><strong>C'è un'osservazione che il gruppo vuole ricordare?</strong></label><p class="hint">Facoltativo</p><textarea id="free" maxlength="500" placeholder="Possiamo scriverla qui…">${esc(state.freeObservation)}</textarea><button class="btn btn-secondary help-btn" id="lookHelp">💡 HO BISOGNO DI UN AIUTO</button>${nav('observe','clues')}`);document.getElementById('free').oninput=e=>{state.freeObservation=e.target.value;save()};document.getElementById('lookHelp').onclick=()=>openHelp('Aiuto per osservare','<p><strong>Prova a osservare:</strong></p><ul><li>le persone e il paesaggio;</li><li>la luce e i colori;</li><li>ciò che sembra fermo o in movimento;</li><li>i segni lasciati dal pennello.</li></ul><p><strong>Non dovete osservare tutto. Scegliete da dove iniziare.</strong></p>')}
function renderClues(){const cards=Object.entries(CASE.clues).map(([k,c])=>`<div class="clue-card ${state.selectedClues.includes(k)?'selected':''}"><button class="clueToggle" data-clue="${k}"><strong>${c.label}</strong>${c.question}<br><span class="small">${state.selectedClues.includes(k)?'SELEZIONATO':'Tocca per selezionare'}</span></button><button class="btn btn-secondary help-btn clueHelp" data-help="${k}">💡 AIUTO</button></div>`).join('');app.innerHTML=layout(`<h2>CERCA GLI INDIZI</h2><p>Osservate di nuovo l'opera.</p><p class="lead"><strong>Quali indizi riuscite a sostenere con ciò che vedete?</strong></p><div class="status warn"><strong>Non dovete trovarli tutti.</strong></div><div class="clue-grid">${cards}</div><p id="clueError" class="error"></p>${nav('look','proof','ABBIAMO TROVATO I NOSTRI INDIZI →',state.selectedClues.length===0)}`);document.querySelectorAll('.clueToggle').forEach(b=>b.onclick=()=>{const k=b.dataset.clue;state.selectedClues=state.selectedClues.includes(k)?state.selectedClues.filter(x=>x!==k):[...state.selectedClues,k];if(state.chosenClue&&!state.selectedClues.includes(state.chosenClue))state.chosenClue='';save();render()});document.querySelectorAll('.clueHelp').forEach(b=>b.onclick=()=>{const c=CASE.clues[b.dataset.help];openHelp(c.label,`<p>${esc(c.help)}</p>`)})}
function renderProof(){if(!state.selectedClues.length){setStep('clues');return}const choices=state.selectedClues.map(k=>`<button class="choice ${state.chosenClue===k?'selected':''}" data-choice="${k}">${CASE.clues[k].label}</button>`).join('');app.innerHTML=layout(`<h2>SCEGLI LA PROVA</h2><p>Confrontate gli indizi che avete trovato.</p><p class="lead"><strong>Qual è quello per cui avete la prova visiva più convincente?</strong></p><div class="choice-row">${choices}</div><hr><label for="evidence"><strong>Dove lo vedete nell'opera?</strong></label><p>Descrivete concretamente che cosa osservate.</p><textarea id="evidence" maxlength="700" placeholder="La nostra prova visiva…">${esc(state.visualEvidence)}</textarea><p class="hint">Scrivete una frase breve e chiara.</p><button class="btn btn-secondary help-btn" id="writeHelp">💡 AIUTO PER SCRIVERE</button>${nav('clues','compare','CONTINUA →',!state.chosenClue||!state.visualEvidence.trim())}`);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const next=b.dataset.choice;if(state.chosenClue!==next){state.chosenClue=next;state.visualEvidence='';save();render()}});document.getElementById('evidence').oninput=e=>{state.visualEvidence=e.target.value;save();document.getElementById('nextBtn').disabled=!state.chosenClue||!state.visualEvidence.trim()};document.getElementById('writeHelp').onclick=()=>openHelp('Aiuto per scrivere','<p>Potete iniziare così:</p><p><strong>«Pensiamo che… perché nell’opera vediamo…»</strong></p><p>oppure</p><p><strong>«La nostra prova è…»</strong></p>')}
function renderCompare(){const no=state.initialAgreement==='No';app.innerHTML=layout(`<h2>CONFRONTATEVI</h2><p class="lead">Prima di concludere, pensate a <strong>come avete preso la vostra decisione</strong>.</p><h3>All'inizio eravate tutti d'accordo sull'indizio da scegliere?</h3><div class="choice-row"><button class="choice agree ${state.initialAgreement==='Sì'?'selected':''}" data-v="Sì">SÌ</button><button class="choice agree ${no?'selected':''}" data-v="No">NO, AVEVAMO IDEE DIVERSE</button></div>${no?`<p><label for="ideas"><strong>Quali idee diverse erano emerse?</strong></label></p><textarea id="ideas" maxlength="500" placeholder="Scrivete in poche parole…">${esc(state.differentIdeas)}</textarea>`:''}<h3>Che cosa vi ha aiutato a decidere insieme?</h3><div class="checks">${[['observation','Abbiamo guardato meglio l’opera'],['zoom','Abbiamo ingrandito un dettaglio'],['discussion','Abbiamo confrontato le nostre idee'],['visualEvidence','Abbiamo cercato una prova visiva'],['other','Altro']].map(([v,l])=>`<label><input type="checkbox" class="factor" value="${v}" ${state.decisionFactors.includes(v)?'checked':''}>${l}</label>`).join('')}</div>${state.decisionFactors.includes('other')?`<p><label for="other"><strong>Che cosa?</strong></label></p><input id="other" type="text" maxlength="300" value="${esc(state.decisionOther)}">`:''}${nav('proof','conclusion','CONTINUA →',!state.initialAgreement||state.decisionFactors.length===0||(no&&!state.differentIdeas.trim())||(state.decisionFactors.includes('other')&&!state.decisionOther.trim()))}`);document.querySelectorAll('.agree').forEach(b=>b.onclick=()=>{state.initialAgreement=b.dataset.v;if(state.initialAgreement==='Sì')state.differentIdeas='';save();render()});const ideas=document.getElementById('ideas');if(ideas)ideas.oninput=e=>{state.differentIdeas=e.target.value;save();validateCompare()};document.querySelectorAll('.factor').forEach(c=>c.onchange=()=>{state.decisionFactors=[...document.querySelectorAll('.factor:checked')].map(x=>x.value);if(!state.decisionFactors.includes('other'))state.decisionOther='';save();render()});const other=document.getElementById('other');if(other)other.oninput=e=>{state.decisionOther=e.target.value;save();validateCompare()}}
function validateCompare(){const b=document.getElementById('nextBtn');if(b)b.disabled=!state.initialAgreement||state.decisionFactors.length===0||(state.initialAgreement==='No'&&!state.differentIdeas.trim())||(state.decisionFactors.includes('other')&&!state.decisionOther.trim())}
function renderConclusion(){const clue=CASE.clues[state.chosenClue]?.label||'';app.innerHTML=layout(`<h2>LA NOSTRA CONCLUSIONE</h2><div class="status"><strong>Indizio scelto:</strong> ${clue}<br><strong>La nostra prova:</strong> ${esc(state.visualEvidence)}</div><p class="lead"><strong>Adesso scrivete insieme la vostra conclusione.</strong></p><p>Massimo 3 righe.</p><textarea id="conclusion" maxlength="300" rows="3" placeholder="La nostra conclusione…">${esc(state.conclusion)}</textarea><button class="btn btn-secondary help-btn" id="conclusionHelp">💡 AIUTO</button>${nav('compare','summary','ABBIAMO FINITO',!state.conclusion.trim())}`);document.getElementById('conclusion').oninput=e=>{state.conclusion=e.target.value;save();document.getElementById('nextBtn').disabled=!state.conclusion.trim()};document.getElementById('conclusionHelp').onclick=()=>openHelp('Aiuto per concludere','<p>Potete iniziare così:</p><p><strong>«In quest’opera abbiamo riconosciuto soprattutto… Lo pensiamo perché…»</strong></p>')}
function payload(){const has=x=>state.decisionFactors.includes(x);return {submissionId:state.submissionId,group:state.group,artist:state.artist,artwork:state.artwork,artworkYear:state.artworkYear,freeObservation:state.freeObservation.trim(),selectedClues:state.selectedClues.map(k=>CASE.clues[k].label.replace(/^\S+\s/,'')).join(' | '),chosenClue:CASE.clues[state.chosenClue].label.replace(/^\S+\s/,''),visualEvidence:state.visualEvidence.trim(),initialAgreement:state.initialAgreement,differentIdeas:state.initialAgreement==='No'?state.differentIdeas.trim():'Non applicabile',decisionObservation:has('observation')?'Sì':'No',decisionZoom:has('zoom')?'Sì':'No',decisionDiscussion:has('discussion')?'Sì':'No',decisionVisualEvidence:has('visualEvidence')?'Sì':'No',decisionOther:has('other')?(state.decisionOther.trim()||'Altro'):'',conclusion:state.conclusion.trim()}}
function renderSummary(){state.status='ready_to_submit';save();const p=payload();app.innerHTML=`<section class="panel summary"><h2>CONTROLLATE IL VOSTRO LAVORO</h2><dl><dt>Gruppo</dt><dd>${esc(p.group)}</dd><dt>Opera</dt><dd>${esc(p.artist)}, <em>${esc(p.artwork)}</em>, ${esc(p.artworkYear)}</dd><dt>Indizio scelto</dt><dd>${esc(p.chosenClue)}</dd><dt>La nostra prova visiva</dt><dd>${esc(p.visualEvidence)}</dd><dt>All'inizio eravamo tutti d'accordo?</dt><dd>${esc(p.initialAgreement)}</dd><dt>Idee diverse emerse</dt><dd>${esc(p.differentIdeas)}</dd><dt>Ci ha aiutato a decidere</dt><dd>${esc(decisionText())}</dd><dt>La nostra conclusione</dt><dd>${esc(p.conclusion)}</dd></dl><div id="sendStatus"></div><div class="nav-row"><button class="btn btn-secondary" data-go="conclusion">← VOGLIAMO MODIFICARE</button><button class="btn" id="sendBtn">INVIA IL NOSTRO LAVORO</button></div></section>`;document.getElementById('sendBtn').onclick=sendWork}
function decisionText(){const m={observation:'Abbiamo guardato meglio l’opera',zoom:'Abbiamo ingrandito un dettaglio',discussion:'Abbiamo confrontato le nostre idee',visualEvidence:'Abbiamo cercato una prova visiva',other:state.decisionOther||'Altro'};return state.decisionFactors.map(x=>m[x]).join(' · ')}
async function sendWork(){const btn=document.getElementById('sendBtn'), box=document.getElementById('sendStatus');btn.disabled=true;state.status='submission_pending';save();const set=t=>box.innerHTML=`<div class="status warn">${esc(t)}</div>`;try{const ok=await API.submitAndVerify(payload(),set);if(ok){S.clear();state={currentStep:'success'};render()}else{state=S.load();state.status='ready_to_submit';save();box.innerHTML='<div class="status warn"><strong>NON RIUSCIAMO ANCORA A CONFERMARE L’INVIO</strong><br>Il vostro lavoro è ancora salvato sul tablet. Potete riprovare senza perdere nulla.</div>';btn.textContent='RIPROVA L’INVIO';btn.disabled=false}}catch(e){state=S.load();state.status='ready_to_submit';save();box.innerHTML=`<div class="status warn"><strong>IL LAVORO NON È STATO CONFERMATO</strong><br>Le risposte sono ancora salvate sul tablet.<br><span class="small">${esc(e.message)}</span></div>`;btn.textContent='RIPROVA L’INVIO';btn.disabled=false}}
function renderSuccess(){progress.classList.add('hidden');zoomBtn.classList.add('hidden');app.innerHTML='<section class="home panel"><div class="status ok"><h2>LAVORO INVIATO ✓</h2><p>Il lavoro del <strong>Gruppo 1</strong> è stato registrato.</p><p>Grazie per aver osservato, discusso e sostenuto la vostra interpretazione con una prova visiva.</p></div><button id="homeBtn" class="btn">TORNA ALL’INIZIO</button></section>';document.getElementById('homeBtn').onclick=()=>{state=null;render()}}
function bindCommon(){document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>setStep(b.dataset.go))}
help.querySelector('#helpClose').onclick=()=>help.close();zoomBtn.onclick=zoomWork;document.getElementById('zoomClose').onclick=()=>zoom.close();
render();
})();
